---
title: Seven Days Wind
timezone: UTC
collections:
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
defaults:
- scope:
    path: ''
    type: pages
  values:
    layout: page
- scope:
    path: ''
    type: posts
  values:
    layout: post
description: 'Descrição

'
baseurl: 
url: https://sevendayswind.com
email: 7dayswind@gmail.com
social:
  bandcamp: https://sevendayswind.bandcamp.com/album/seven-days-wind
  facebook: http://facebook.com/sevendayswind
  instagram: http://instagram.com/sevendayswind
  youtube: http://youtube.com/windsondantas
  soundcloud: http://soundcloud.com/sevendayswind
  spotify: https://open.spotify.com/artist/6KWPp7jtiiVG1iav7AUwrY
whatsapp:
  "+55 (13) 99773-3107": "+5513997733107"
  "+55 (11) 99729-2555": "+5511997292555"
exclude:
- gulpfile.js
- README.md
- desktop.ini
markdown: kramdown
sass:
  style: compressed
